version: '3.4'

services:
  db:
    restart: unless-stopped
    image: mezis/docker-cassandra
    build: .
    volumes:
      - data:/var/lib/cassandra
    environment:
      CASSANDRA_MAX_HEAP_SIZE: "384M"
      CASSANDRA_HEAP_NEWSIZE:  "64M"
    ports:
      - "9042:9042/tcp"
volumes:
  data:
